modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
mixinConfigs="blessingofpandora.mixins.json"

description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curseofpandora"
    mandatory=true
    versionRange="[2.4.26,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[5.4.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[15,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="irons_spellbooks"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="goety"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="touhou_little_maid"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="attributeslib"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"
